// <auto-generated />
using EFTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFTest.Migrations
{
    [DbContext(typeof(PopsCarsContext))]
    [Migration("20231026200225_idchanges")]
    partial class idchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFTest.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Color = "Blue",
                            Make = "Chevy",
                            Model = "Biscayne",
                            UserId = 0,
                            Year = 1968
                        },
                        new
                        {
                            CarId = 2,
                            Color = "Blue",
                            Make = "Ford",
                            Model = "Fairlane",
                            UserId = 0,
                            Year = 1967
                        },
                        new
                        {
                            CarId = 3,
                            Color = "Turquoise Blue/Green",
                            Make = "Volkswagen",
                            Model = "Beetle",
                            UserId = 0,
                            Year = 1965
                        },
                        new
                        {
                            CarId = 4,
                            Color = "Green",
                            Make = "Chevy",
                            Model = "Impala",
                            UserId = 0,
                            Year = 1966
                        },
                        new
                        {
                            CarId = 5,
                            Color = "Green",
                            Make = "Ford",
                            Model = "Pinto",
                            UserId = 0,
                            Year = 1972
                        },
                        new
                        {
                            CarId = 6,
                            Color = "Beige",
                            Make = "Volkswagen",
                            Model = "Beetle",
                            UserId = 0,
                            Year = 1964
                        },
                        new
                        {
                            CarId = 7,
                            Color = "Beige",
                            Make = "Nissan",
                            Model = "Datsun",
                            UserId = 0,
                            Year = 1967
                        },
                        new
                        {
                            CarId = 8,
                            Color = "Maroon",
                            Make = "Ford",
                            Model = "Fairlane",
                            UserId = 0,
                            Year = 1963
                        },
                        new
                        {
                            CarId = 9,
                            Color = "Light Blue",
                            Make = "Dodge",
                            Model = "Monaco",
                            UserId = 0,
                            Year = 1975
                        },
                        new
                        {
                            CarId = 10,
                            Color = "Blue",
                            Make = "Ford",
                            Model = "Van E100",
                            UserId = 0,
                            Year = 1976
                        },
                        new
                        {
                            CarId = 11,
                            Color = "Maroon",
                            Make = "Ford",
                            Model = "LTD",
                            UserId = 0,
                            Year = 1979
                        },
                        new
                        {
                            CarId = 12,
                            Color = "Silver",
                            Make = "Toyota",
                            Model = "Celica",
                            UserId = 0,
                            Year = 1983
                        },
                        new
                        {
                            CarId = 13,
                            Color = "Brown",
                            Make = "Volkswagen",
                            Model = "Beetle",
                            UserId = 0,
                            Year = 1965
                        },
                        new
                        {
                            CarId = 14,
                            Color = "Brown/Red Stolen",
                            Make = "Toyota",
                            Model = "Corolla",
                            UserId = 0,
                            Year = 1977
                        },
                        new
                        {
                            CarId = 15,
                            Color = "White",
                            Make = "Chevy",
                            Model = "Monte Carlo",
                            UserId = 0,
                            Year = 1973
                        },
                        new
                        {
                            CarId = 16,
                            Color = "Blue",
                            Make = "Chevy",
                            Model = "Chevette",
                            UserId = 0,
                            Year = 1976
                        },
                        new
                        {
                            CarId = 17,
                            Color = "Brown",
                            Make = "Chevy",
                            Model = "Malibu",
                            UserId = 0,
                            Year = 1975
                        },
                        new
                        {
                            CarId = 18,
                            Color = "Blue",
                            Make = "Pontiac",
                            Model = "Firebird",
                            UserId = 0,
                            Year = 1976
                        },
                        new
                        {
                            CarId = 19,
                            Color = "Red",
                            Make = "Oldsmobile",
                            Model = "Omega",
                            UserId = 0,
                            Year = 1974
                        },
                        new
                        {
                            CarId = 20,
                            Color = "Silver/BlackGold",
                            Make = "Nissan",
                            Model = "Datsun 2 Plus 2",
                            UserId = 0,
                            Year = 1977
                        },
                        new
                        {
                            CarId = 21,
                            Color = "Brown",
                            Make = "Ford",
                            Model = "Grenada",
                            UserId = 0,
                            Year = 1975
                        },
                        new
                        {
                            CarId = 22,
                            Color = "Silver/Blue",
                            Make = "Toyota",
                            Model = "Celica",
                            UserId = 0,
                            Year = 1985
                        },
                        new
                        {
                            CarId = 23,
                            Color = "Brown",
                            Make = "Jeep",
                            Model = "Wagoneer",
                            UserId = 0,
                            Year = 1975
                        },
                        new
                        {
                            CarId = 24,
                            Color = "Blue",
                            Make = "Oldsmobile",
                            Model = "Delta 88",
                            UserId = 0,
                            Year = 1985
                        },
                        new
                        {
                            CarId = 25,
                            Color = "Beige",
                            Make = "Chevy",
                            Model = "Chevelle Wagon",
                            UserId = 0,
                            Year = 1967
                        },
                        new
                        {
                            CarId = 26,
                            Color = "White",
                            Make = "Chevy",
                            Model = "Malibu",
                            UserId = 0,
                            Year = 1981
                        },
                        new
                        {
                            CarId = 27,
                            Color = "Red",
                            Make = "Jeep",
                            Model = "Wrangler",
                            UserId = 0,
                            Year = 1990
                        },
                        new
                        {
                            CarId = 28,
                            Color = "Blue",
                            Make = "Oldsmobile",
                            Model = "Aurora",
                            UserId = 0,
                            Year = 1996
                        },
                        new
                        {
                            CarId = 29,
                            Color = "Grey",
                            Make = "Oldsmobile",
                            Model = "Cutlass",
                            UserId = 0,
                            Year = 1975
                        },
                        new
                        {
                            CarId = 30,
                            Color = "Silver",
                            Make = "Mazda",
                            Model = "926",
                            UserId = 0,
                            Year = 1993
                        },
                        new
                        {
                            CarId = 31,
                            Color = "Blue/Off White Blueish",
                            Make = "Austin",
                            Model = "Healey",
                            UserId = 0,
                            Year = 1971
                        },
                        new
                        {
                            CarId = 32,
                            Color = "Black",
                            Make = "Toyota",
                            Model = "Camry",
                            UserId = 0,
                            Year = 2000
                        },
                        new
                        {
                            CarId = 33,
                            Color = "Blue",
                            Make = "Toyota",
                            Model = "Tacoma",
                            UserId = 0,
                            Year = 2008
                        },
                        new
                        {
                            CarId = 34,
                            Color = "Black",
                            Make = "Ford",
                            Model = "Mustang",
                            UserId = 0,
                            Year = 1965
                        },
                        new
                        {
                            CarId = 35,
                            Color = "Green",
                            Make = "Chevy",
                            Model = "210/Belair",
                            UserId = 0,
                            Year = 1954
                        });
                });

            modelBuilder.Entity("EFTest.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("EFTest.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CarId = 0,
                            UserName = "Pop"
                        });
                });

            modelBuilder.Entity("EFTest.Models.Car", b =>
                {
                    b.HasOne("EFTest.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
