

namespace TestForPopsCars
{
    public class ServiceTest
    {
        //create unit tests for my service class

        // all code below was generated by gitHub copilot
        [TestMethod]
        public void GetAllCars_Returns_List_Of_Cars()
        {
            //Arrange
            var mockRepo = new Mock<ICarsRepository>();
            mockRepo.Setup(repo => repo.GetAll()).Returns(GetTestCars());
            var service = new Service(mockRepo.Object);

            //Act
            var result = service.GetAllCars();

            //Assert
            Assert.AreEqual(3, result.Count);
        }
        [TestMethod]
    }
}
